[package]
name = "i3_workspace_notifier"
version = "0.1.0"
authors = ["rektrex <psaimanideep@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i3ipc = "0.10.1"
dirs = "2.0.2"
